### ISSUE TITLE
[FEATURE] Edit channels in website

### ISSUE THREAD

**Issue by realmeric** [Discord-Templates/Bugs-and-Feedbacks#26]
**Is your feature request related to a problem? Please describe.**
i don't want to edit template channels in Discord when i want to change it

**Describe the feature you'd like**
An Edit button in template page and if you click it you can edit your template channels etc.

**Additional context**
Bruh no

**Comment by eri** [comment]
That’s a technical constraint. Template links generated through your Discord server settings should match with the data displayed on the website and cannot be edited.

We could maybe make this editing process less boring by adding an update button on the edit section of templates.

In the future, turning templates into « bot use only » templates to allow editing might be a solution for that, however due to the limitative nature of this solution (disabling the Use > New server feature), it’s currently not something we would like to implement.
